### ISSUE TITLE
How does "-m glob" work?

### ISSUE THREAD

**Issue by mgsloan** [bos/criterion#101]
I have benchmarks named things like `decode/1kb normal (Vector Int32)`, etc.  I am familiar with using `-m` with hspec.  There, you just give a substring of the benchmark(s) you want, like `-m normal`.

criterion does not seem to have "is substring" as a matching predicate.  I'd find this very useful.  Ideally it would be the default so that people can use the same matching syntax as with hspec.

In lieu of substring matching, I tried using glob with `-m glob *normal*`, but it didn't match any benchmarks.  I also tried `-m glob '*normal*'`, but no such luck :(

**Comment by rrnewton** [comment]
Yeah, we just use whole names, and come to think of it I'm not sure how/if the glob matching works either.

**Comment by jberryman** [comment]
Glob matching is implemented by the Glob library, which you can find documented here; http://hackage.haskell.org/package/Glob-0.7.13/docs/System-FilePath-Glob.html . Globbing on the benchmarks works as though they were filepaths (I'll bet that's why bos chose to use "/" as the separator), so you need to be mindful of the "matches all except the path separator" mentions there. I don't fully grok it yet, but have been able to do things like:

```
» dist/build/bench-realistic/bench-realistic -m glob "**/Text**/*"                                                                                            
benchmarking Text/strict/5/siphash64_1_3
...

» dist/build/bench-realistic/bench-realistic -m glob "**/siphash***/*"        
benchmarking ByteString/strict/5/siphash64_1_3
...
```

**Comment by mgsloan** [comment]
Thanks @jberryman !  I indeed didn't realize that * wouldn't match the /.
