### ISSUE TITLE
Report measurements for --iters (and fix parsing errors)

### ISSUE THREAD

**Issue by rrnewton** [bos/criterion#114]
@RyanGlScott is looking into command parsing errors that prevent `--iters` to be used with other command line options.

Further, it would be great to report SOME information from such a run.  Criterion cannot do a regression with just one batch of iters, but it can at least report the time.

**Comment by RyanGlScott** [comment]
Oh, well finding out the source of the parser "error" turned out to be [surprisingly easy](https://github.com/bos/criterion/blob/32afe61935e55662425d535df2edbfd30bb79afd/Criterion/Main/Options.hs#L84-L93):

```haskell
parseWith :: Config -> Parser Mode
parseWith cfg =
    (matchNames (Run <$> config cfg)) <|>
    runIters <|>
    (List <$ switch (long "list" <> short 'l' <> help "List benchmarks")) <|>
    (Version <$ switch (long "version" <> help "Show version info"))
```

It turns out that `--iters` is an entirely different execution mode than the mode that allows specifying other options.

How easy it is to fold `--iters` into the other options, I don't know...

**Comment by merijn** [comment]
As far as I can tell the fairly trivial change in my PR #136 should also fix this.
