### ISSUE TITLE
Criterion 1.1.4.0 not producing HTML reports

### ISSUE THREAD

**Issue by erikd** [bos/criterion#126]
With criterion 1.1.4.0, with the benchmark run as (in a cabal sandbox) I get:
```
> dist/build/bench/bench --no-gc -o bench.html
benchmarking Write to ByteString/Binary
...
...
bench: TemplateNotFound "default"
```

**Comment by erikd** [comment]
There also seems to be no entry in the `changelog.md` file for the 1.1.4.0 release.

**Comment by RyanGlScott** [comment]
I haven't been able to reproduce the particular error you're seeing (`TemplateNotFound "default"`) with or without a sandbox, but this is with my own code. Do you mind sharing the code that you're trying to run?

Separately, we should also consolidate all the `changelog` entries after 1.1.1.0 into 1.1.4.0, since there weren't any Hackage releases between those version numbers.

**Comment by erikd** [comment]
```
git clone https://github.com/erikd/fastpack
cd fastpack
git co 52bbe547aeafb4b41 -b test
cabal sandbox init
cabal install --dependencies-only --enable-benchmarks
cabal configure  --enable-benchmarks
cabal build
dist/build/bench/bench -o bench.html
```
With that procedure I get `TemplateNotFound` every time.

**Comment by RyanGlScott** [comment]
Hrm, I've tried that on two Ubuntu 14.04 machines (one in a Docker image) with GHC 8.0.1 / `cabal-install-1.14.0.1`, but couldn't reproduce it.

It's a bit baffling that this happens, since [`templates`](https://github.com/bos/criterion/blob/f117bec84c9bf460549fa565b8f30fac075a7db7/Criterion/Report.hs#L74)`/`[`default`](https://github.com/bos/criterion/blob/f117bec84c9bf460549fa565b8f30fac075a7db7/Criterion/Main/Options.hs#L81)`.tpl` should always just be loaded, since it's listed as a [`data-file` in `criterion.cabal`](https://github.com/bos/criterion/blob/ab636106c596e689c455517d42521dc57f8cbc98/criterion.cabal#L23).

For clarification, when you say you get this error occasionally, does the error happen when you run `dist/build/bench/bench -o bench.html` successively after installing it once? Or does it require reinstalling the sandbox to trigger the non-determinacy?

**Comment by erikd** [comment]
This seems to be related with whether --no-gc is added to the command line when I run the benchmark. Adding is seems to make bad things happen (silently).

**Comment by erikd** [comment]
Bah, figured it out. I sometimes use a custom template and the terms in the default templates that are replaced had changed.
```
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
     <title>criterion report</title>
     <script language="javascript" type="text/javascript">
-      {{#include}}js/jquery-2.1.1.min.js{{/include}}
+      {{js-jquery}}
     </script>
     <script language="javascript" type="text/javascript">
-      {{#include}}js/jquery.flot-0.8.3.min.js{{/include}}
+      {{js-flot}}
     </script>
     <script language="javascript" type="text/javascript">
       {{#include}}js/jquery.criterion.js{{/include}}
```
Would be nice if there was an actual error or warning printed when the template replacement failed.

**Comment by RyanGlScott** [comment]
You mentioned that `--no-gc` was an important part of the equation in https://github.com/bos/criterion/issues/126#issuecomment-260777656, but in https://github.com/bos/criterion/issues/127#issuecomment-260884000 you seemed to be doubting that claim.

Also, even after trying out `--template` (as you recommended in https://github.com/bos/criterion/issues/127#issuecomment-261043624), I still am unable to reproduce this issue. Is this still affecting you? If so, can you give me some guidance on how one might trigger it?

**Comment by erikd** [comment]
I can't right now. I'll try some more after I work.

**Comment by erikd** [comment]
I've managed to re-produce this problem. Might as well close it.
