### ISSUE TITLE
criterionerror-exe: Prelude.undefined

### ISSUE THREAD

**Issue by bwroga** [bos/criterion#155]
This program compiles:

```
module Main where

import Criterion.Main

main :: IO ()
main = defaultMain [
  env ((return (1,2)) :: IO (Int,Int)) (\(x,y) -> bench "a" $ nf (x+) y)
  ]
```

but when I run it with the argument "a", I get the following

> criterionerror-exe: Prelude.undefined
> CallStack (from HasCallStack):
>   error, called at libraries/base/GHC/Err.hs:79:14 in base:GHC.Err
>   undefined, called at ./Criterion/Types.hs:591:48 in criterion-1.2.2.0-H2DCDRNKB7q2XSr6H1Wlsz:Criterion.Types

This runs without any problems

```
module Main where

import Criterion.Main

main :: IO ()
main = defaultMain [
  env ((return 1) :: IO Int) (\x -> bench "b" $ nf (1+) x)
  ]

```

**Comment by RyanGlScott** [comment]
This is happening due to a nuance in the way `env` works, which is documented [here](http://hackage.haskell.org/package/criterion-1.2.2.0/docs/Criterion-Types.html#v:env):

> **Lazy pattern matching**. In situations where a "real" environment is not needed, e.g. if a list of benchmark names is being generated, `undefined` will be passed to the function that receives the environment. This avoids the overhead of generating an environment that will not actually be used.
>
> The function that receives the environment must use lazy pattern matching to deconstruct the tuple, as use of strict pattern matching will cause a crash if `undefined` is passed in.

Gruesome, yes. But so it goes. Thus, you can fix your code by changing it to `(\ ~(x,y) -> bench "a" $ nf (x+) y)`. (The second example is not subject to this problem since it doesn't pattern match on a constructor.)

That being said, `undefined` does not give terribly helpful advice when you do screw up. It would be nice to have it say something like `"Perhaps you forgot to use lazy pattern matching in the function which constructs benchmarks from an environment?"`.

**Comment by bwroga** [comment]
Thanks!
