### ISSUE TITLE
Providing a tuple to `env` causes "could not determine the list of your benchmarks ..." error.

### ISSUE THREAD

**Issue by kindaro** [bos/criterion#159]
Let me start with an excerpt from my terminal:

    % ./CriterionLeft.hs
    CriterionLeft.hs: Criterion.env could not determine the list of your benchmarks
    since they force the environment (see the documentation for details)
    CallStack (from HasCallStack):
      error, called at ./Criterion/Internal.hs:202:7 in
    criterion-1.1.4.0-EKiMF3PtlUVEKNn1brKmII:Criterion.Internal

Even though the error message points to the documentation, I believe this behaviour is erroneous, and in two ways:
1. In the specific case at hand, I don't see any reason for crashing at all.
1. I could not possibly thoughtfully read the whole available commentary to the package. I read the parts that seem relevant (`Criterion.env` & `Criterion.Internal.for`) and what I saw is "if you need to create an environment that contains multiple values, simply pack the values into a tuple" which describes precisely what I do in this case. If there are other points to be extracted from the documentation, they should be specifically pointed to in this very error message.

The kind reader can see for themself: [github.com/kindaro/criterion-wut](https://github.com/kindaro/criterion-wut)

---

Though the attentive reader may notice `criterion-1.1.4.0` in the terminal ouptut excerpt above, I did test with `criterion-1.2.2.0` as well, to the same outcome. Generally, I used the latest available nightly `stack` snapshot.

**Comment by RyanGlScott** [comment]
So there's two matters at hand:

1. _Why_ this crashed
2. The error message you got

I'll address each of these points in order.

-----

1. The problem is simply that you don't lazily pattern-match on the tuple argument of `unrelatedBenchmark`. It's a bit strange that you have to do this, but there's a reason for it, as explained in the Haddocks for [`env`](http://hackage.haskell.org/package/criterion-1.2.2.0/docs/Criterion-Main.html#v:env):

   > **Lazy pattern matching**. In situations where a "real" environment is not needed, e.g. if a list of benchmark names is being generated, `undefined` will be passed to the function that receives the environment. This avoids the overhead of generating an environment that will not actually be used.
   >
   > The function that receives the environment must use lazy pattern matching to deconstruct the tuple, as use of strict pattern matching will cause a crash if `undefined` is passed in.

2. Yes, the error message you received does not do a terribly good job of telling you where to look to find this. It's worth noting, though, that in `criterion` HEAD there's a way to trigger another error message that does (IMO) a better job of explaining this:

   ```
   $ ./Bug fdsa
   Bug: Criterion atttempted to retrieve a non-existent environment!
           Perhaps you forgot to use lazy pattern matching in a function which
           constructs benchmarks from an environment?
           (see the documentation for `env` for details)
   
   CallStack (from HasCallStack):
     error, called at ./Criterion/Types.hs:605:19 in criterion-1.2.2.0-I3rygZj7SdY52Xvi157YCX:Criterion.Types
   ```

   Would you find this error message more useful in this scenario? If so, I could easily rework `criterion` to throw this error as well when you don't give _any_ arguments to the executable, as you do with `CriterionLeft`.

**Comment by kindaro** [comment]
@RyanGlScott Thank you for your explanation. Lazy pattern matching with `~` must be a somewhat obscure feature of Haskell, I never had to use it before. So when I read this part, my thoughts were like "Haskell defaults to laziness, so pattern matching must be lazy per se." Turns out not to be so. The addition of `~` rectifies the issue.

I understand that most users of Criterion already have a degree of mastery over performance issues that implies extensive knowledge of laziness modifiers, such as `~` and `!`. But maybe the documentation might still be made more novice friendly? For example, instead of saying "must use lazy pattern matching" may it rather say something along the lines of "must use [lazy pattern matching](https://wiki.haskell.org/Lazy_pattern_match) (for example: `~(x, y)`, not `(x,y)`)" ?

I must say that, after reading about lazy pattern matching, the documentation for `env` is still not clear to me. For example, I don't know at what point and in which case a *"list of benchmark names"* would have to be being generated, and why this business can't be dealt with automagically.

**Comment by RyanGlScott** [comment]
> Lazy pattern matching with `~` must be a somewhat obscure feature of Haskell, I never had to use it before.

I personally wouldn't say it's an obscure feature—it is [a part of the Haskell Report](https://www.haskell.org/onlinereport/exps.html#sect3.17.1), making it pretty standard as far as features go (as opposed to GHC-specific extensions).

> But maybe the documentation might still be made more novice friendly? For example, instead of saying "must use lazy pattern matching" may it rather say something along the lines of "must use [lazy pattern matching](https://wiki.haskell.org/Lazy_pattern_match) (for example: `~(x, y)`, not `(x,y)`)" ?

Would you be OK with changing the second part of the Haddocks to this?

"The function that receives the environment must use lazy pattern matching to deconstruct the tuple (e.g., `~(x, y)`, not `(x, y)`), as use of strict pattern matching will cause a crash if `undefined` is passed in."

> For example, I don't know at what point and in which case a *"list of benchmark names"* would have to be being generated, and why this business can't be dealt with automagically.

Think of it like this: every `criterion` program essentially looks something like this:

```haskell
main = defaultMainWith myConfig [
         bench "bench1" $ ...
       , bench "bench2" $ ...
       , bench "bench3" $ ...
       ...
       ]
```

For various reasons, `criterion` needs to internally construct a list of benchmark names to run before it proceeds to do so. Finding the name of a `bench`'s name is easy, since it's direct to access. But what if you had a benchmark like this?

```haskell
main = defaultMainWith myConfig [
         env setupEnv $ \blah -> bench "envBench" $ ...
       ]
```

Here, the benchmark name is buried underneath a lambda, so literally the only way `criterion` can retrieve this name is by passing _something_ to this lambda. Moreover, this environment lambda's argument can be of any type, so the only thing we can realistically pass it is `undefined`. It's somewhat strange, but _c'est la vie_.

**Comment by kindaro** [comment]
I kind of understand. Thank you very much for spending time on a thorough explanation. Will it be helpful if I edit the documentation and create a pull request?

**Comment by RyanGlScott** [comment]
> Will it be helpful if I edit the documentation and create a pull request?

Absolutely!

**Comment by RyanGlScott** [comment]
In addition to #164, which improves the documentation for `env`, I've also changed the error message to match the output shown in https://github.com/bos/criterion/issues/159#issuecomment-334624626, which is more informative.
