### ISSUE TITLE
The outputfile generates some bars in barely visible colors.

### ISSUE THREAD

**Issue by AndreasPK** [bos/criterion#170]
There is too little contrast between one of the bar colors and the background.

![grafik](https://user-images.githubusercontent.com/5500646/33805000-55356a06-ddb1-11e7-9ca8-04b57b96345b.png)

**Comment by RyanGlScott** [comment]
Thanks for the bug report. If you're following at home and want to reproduce this bug yourself, you can build the following `criterion` example:

```haskell
module Main where

import Control.Lens.Indexed
import Criterion.Main

main :: IO ()
main =
    defaultMain
  $ imap (\i b -> bgroup ("group" ++ show i) [bench "test" b])
  $ replicate 70 (whnf ('a':) "b")
```
```
$ ghc Bug.hs
$ ./Bug -o bug1.html
```

This does indeed produce some benchmark group colors that are hard to see:

![criterion-before](https://user-images.githubusercontent.com/2364661/33805385-00bf05c0-dd86-11e7-9b59-983c1bbfb0cb.png)

Luckily, it turns out that this has already been fixed upstream, thanks to #150. Now, benchmark groups simply cycle through a predetermined set of colors. Here is what the program above would generate now:

![criterion-after](https://user-images.githubusercontent.com/2364661/33805394-21ee648e-dd86-11e7-9f9c-788d3cf41321.png)

(Don't be too bothered too much by the noisiness of those results—I was running this on a laptop with several other concurrent processes.)

Does that work for you, @AndreasPK? If so, I can cut a new release soon with this fix.

**Comment by AndreasPK** [comment]
@RyanGlScott Yes the git version works fine for me.

Thanks for the fast response!

**Comment by RyanGlScott** [comment]
Good to know. I've uploaded [`criterion-1.2.6.0`](http://hackage.haskell.org/package/criterion-1.2.6.0) to Hackage with the necessary fixes.
