### ISSUE TITLE
Criterion never ends when run by stack bench --profile

### ISSUE THREAD

**Issue by t3hmrman** [bos/criterion#214]
Having a real headscratcher -- working on a tiny data-sketching library and I'm trying to do some benchmarking, but I'm finding that `criterion` loops endlessly for some reason when run with `stack bench --profile` (`stack bench` works great):

`package.yaml`:
```yaml
benchmarks:
  countmin-bench:
    main: Bench.hs
    source-dirs: bench
    dependencies:
      - countmin
      - criterion
      - QuickCheck

## The next few lines don't work commented or uncommented
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
```

`bench/Bench.hs`:
```haskell
{-# LANGUAGE NumericUnderscores #-}
import RIO
import Criterion.Main (defaultMain, bgroup, env, nf, bench)

import Data.Maybe (fromJust)
import BenchData (genRandomStrings)
import Hashes.FarmHash (hFarmHash)
import Hashes.MD5 (hMD5)
import Hashes.SHA1 (hSHA1)
import Lib (buildSketch, Sketch, CountMin(..))

-- | Default sketch, w/ all available hask fns used
defaultSketch :: Sketch
defaultSketch = fromJust $ buildSketch [hMD5, hFarmHash, hSHA1]

main :: IO ()
main = defaultMain [
        env (genRandomStrings 100_000) $ \ ~(values, _) ->
            bgroup "counting random strings (1)" [ bench "w/ Sketch" $ nf (totalCount . foldl' increment defaultSketch) values ]
       ]

-- main :: IO ()
-- main = genRandomStrings 100_000
--        >>= \(values, _) -> pure (foldl' increment defaultSketch values)
--        >>= putStrLn . show . totalCount
```

The commented out alternative `main` runs to completion w/ `stack bench --profile` -- it's not even doing any actual benchmarking/measurement, but I get the space usage I was after. When I run the uncommented code (which I *think* is a decent `criterion` main function), `stack bench --profile` never returns (after a while, I can see a partially written `.prof` with a *ton* of runs.

Here's the top portion of the `.prof` file left over when I stop `stack bench --profile` with `^C`:

```
	Mon May 27 23:11 2019 Time and Allocation Profiling Report  (Final)

	   countmin-bench +RTS -p -RTS

	total time  =       32.16 secs   (32162 ticks @ 1000 us, 1 processor)
	total alloc = 38,942,052,296 bytes  (excludes profiling overheads)

COST CENTRE         MODULE                               SRC                                                   %time %alloc

increment           Lib                                  src/Lib.hs:(33,5)-(62,59)                              33.7   14.2
nf'.go.y            Criterion.Measurement.Types.Internal src/Criterion/Measurement/Types/Internal.hs:49:28-35   27.0   56.9
primitive           Control.Monad.Primitive              Control/Monad/Primitive.hs:97:3-16                      5.2    2.2
randomIvalInteger   System.Random                        System/Random.hs:(468,1)-(489,76)                       5.0    4.1
createBlock256      System.Random.TF.Gen                 src/System/Random/TF/Gen.hs:(41,1)-(47,26)              4.0    3.5
mash                System.Random.TF.Gen                 src/System/Random/TF/Gen.hs:(117,1)-(126,29)            3.1    1.3
>>=.\.(...)         Test.QuickCheck.Gen                  Test/QuickCheck/Gen.hs:68:15-35                         1.8    0.9
tfGenSplit          System.Random.TF.Gen                 src/System/Random/TF/Gen.hs:(166,1)-(173,35)            1.7    4.4
randomIvalInteger.f System.Random                        System/Random.hs:(486,8)-(489,76)                       1.6    0.3
>>=.\               Test.QuickCheck.Gen                  Test/QuickCheck/Gen.hs:(66,7)-(69,20)                   1.4    0.0
split               System.Random.TF.Gen                 src/System/Random/TF/Gen.hs:180:3-20                    1.2    0.6
mkTFGen             System.Random.TF.Gen                 src/System/Random/TF/Gen.hs:(133,1)-(134,36)            1.1    3.8
tfGenNext'          System.Random.TF.Gen                 src/System/Random/TF/Gen.hs:(157,1)-(163,32)            0.8    2.5
randomIvalIntegral  System.Random                        System/Random.hs:462:1-71                               0.8    1.2
```

Just a note, I'm also aware of [`weigh`](https://github.com/fpco/weigh) and plan to give it a try (instead of using `stack --profile`), but was perplexed by the behavior above.

[EDIT] - Additionally, when I use a hardcoded list of values (rather than the random generation), it still doesn't return, here's what I see after stopping it early (w/ `^C`):

```
	Mon May 27 23:15 2019 Time and Allocation Profiling Report  (Final)

	   countmin-bench +RTS -p -RTS

	total time  =       46.13 secs   (46132 ticks @ 1000 us, 1 processor)
	total alloc = 147,537,374,176 bytes  (excludes profiling overheads)

COST CENTRE  MODULE                               SRC                                                         %time %alloc

nf'.go.y     Criterion.Measurement.Types.Internal src/Criterion/Measurement/Types/Internal.hs:49:28-35         42.7   27.3
incrementStr Types                                src/Types.hs:37:5-54                                         30.3   64.5
increment    Lib                                  src/Lib.hs:(33,5)-(62,59)                                    23.6    8.2
nf'.go       Criterion.Measurement.Types.Internal src/Criterion/Measurement/Types/Internal.hs:(48,5)-(50,49)    1.8    0.0
```

Apologies the code changes a *tiny* bit -- I use `incrementStr` instead of `increment` but regardless, it's still weird that it just hangs... I must be using `nf` wrong or something.

[EDIT2] - I've also tried with `whnf` instead of `nf`, same result

**Comment by RyanGlScott** [comment]
I'm afraid I can't say whether this is a bug or not simply because there's no way for me to reproduce this. The example depends on some `countmin` library (which is not on Hackage) and a mysterious `Lib` module (which I have no idea where it may come from). There's also several other external dependencies that I don't recognize, so it's difficult to say whether there are any adverse effects from that code or not, as I'm not familiar with them.

Trimming the example down to something with as few dependencies as possible would be helpful.

**Comment by t3hmrman** [comment]
Hi @RyanGlScott my apologies -- I thought it might be something really obvious with my possible misuse of `criterion` -- the code will be/is open source all the code (it's for a short blog post), please find it @ [`mrman/haskell-countmin` on GitLab](https://gitlab.com/mrman/haskell-countmin/tree/develop).

I assume you *don't* want to look through all that random code, so I'll try and make a minimal subset as an example.

**Comment by t3hmrman** [comment]
Hey so I'm not sure what was wrong, it might have something to do with my `Sketch` type not implementing `NFData` but in the meantime I got around it by using `nfIO` to avoid that requirement:

```haskell
main :: IO ()
main = defaultMain [
        bgroup "counting random strings (1)" [ bench "w/ Sketch" $ nfIO $ pure $ totalCount (foldl' incrementStr defaultSketch emails) ]
       ]
```
Not ideal, but it at least gets me past the problem I was having for now.

I'm going to see if I can implement `NFData` for my `Sketch` type (it couldn't be automatically derived because it contains some functions, IIRC).

**Comment by bravit** [comment]
I think I've got the same behavior. Consider this code in `Bench.hs`:
```
import Criterion.Main

main = defaultMain [
    bench "xxx" $ nf head "xxx"
  ]
```
from the package with the following cabal-file:
```
cabal-version: 1.12
name:           test-criterion
version:        0.1
build-type:     Simple

executable bench
  main-is: Bench.hs
  build-depends:
      base >=4.10 && <4.13
    , criterion >=1.4 && <1.6
  default-language: Haskell2010
```

Now, running `cabal new-run --enable-profiling --ghc-options=-fprof-auto` never ends (after successful compilation and starting the executable) with most of the time spending in `nf'.go.y` from `Criterion.Measurement.Types.Internal`. I have the same behavior for GHC 8.6.5 and 8.4.4. Compiling with `ghc -prof -fprof-auto` leads to the same effect. Removing `-fprof-auto` or switching to `-fprof-auto-top` fixes this. 

I think, `stack bench --profile` provides the same flags to GHC leading to the same behavior.

**Comment by RyanGlScott** [comment]
@bravit, thanks for the example! I am able to reproduce the issue on 64-bit Linux as well.

It's rather strange that this loops forever with `-fprof-auto` but terminates without it, which leads me to suspect that there is a GHC issue involved. Just to be safe, I've filed an issue [here](https://gitlab.haskell.org/ghc/ghc/issues/17016) about it.

**Comment by osa1** [comment]
I think this is a criterion bug and it's still not fixed. I wrote a summary of the problem in the [GHC issue](https://gitlab.haskell.org/ghc/ghc/issues/17016).

**Comment by RyanGlScott** [comment]
If this is a `criterion` bug, then it's one that's made extremely difficult to fix due to GHC infelicities. In particular, it's rather stunning that compiling `runBenchmark`/`measure` with `-fprof-auto` (or indeed, without optimizations at all, as in `-O0`) would make the timing iteration run _faster_. The `runBenchmark`/`measure` functions were carefully tuned by @patrickdoc in order to ensure that enough data is generated (that runs for a statistically significant length of time to count), and the fact that compiling `criterion-measurement` with `-fprof-auto` and/or `-O0` makes the inner benchmarking loop run near instantaneously throws all of the tuning assumptions out the window. I'm not sure how we could reasonably fix this without implementing some kind of full auto-tuning pass to counteract this.

Thoughts, @patrickdoc?

**Comment by osa1** [comment]
I think `-prof` only incidentally triggers the bug -- to reproduce all you need is a fast-enough program so that measured time is small enough. See [my comment][1] in GHC issue tracker. All you need is measured time smaller than 0.03 (I don't know the unit).

[1]: https://gitlab.haskell.org/ghc/ghc/issues/17016#note_216952

**Comment by patrickdoc** [comment]
I'm on mobile, so forgive me if I miss anything.

@osa1 the threshold logic you are pointing to should not actually cause a problem. In fact, it is designed to cover this exact case, namely very fast functions.

I don't know/remember how the threshold was chosen, but the idea was that if the measurement is too small, then the report will not be very reliable. So instead what we do is run the function for an increasing number of iterations until the combined run time is greater than the threshold, then divide by iterations.

This means fast functions will have many runs that are not counted. Since it is fast, these extra runs don't actually cost us much.

---

The reason I made changes in the first place was actually for a similar problem, so I do have a guess what the issue is.

Above someone mentioned that most of the time is spent in nf'.go.y, which is actually a good thing. If I am remembering correctly, that is the line that executes your code to be benchmarked. So most of the execution time is running your code.

My money is on this being a GC issue. Criterion manually runs performGC before and after each loop of the benchmark. This is partially to make the runs cleaner, but it is also where we get the start/end time from the RTS.

I definitely removed 2/4 performGCs, and I "think" I changed the other two to performMinorGC.

Looking at some of the total alloc above, it seems we might have some very large resident memory, which leads to some slow GC times.

Dumping the rts stats for user vs gc time should be enough to test my hypothesis.

**Comment by osa1** [comment]
@patrickdoc have you read my explanation in the GHC issue? I still think the criterion function is the problem, and I explained exactly what the problem is. Just to summarize here

```
let overThres = max 0 (measTime m - threshold) + prev
```

For functions that run fast enough `measTime` will be smaller than `threshold`, and `prev` will be 0 (the initial value, which will never be updated), so this variable will always be 0, and `overThresh > threshold * 10` will never hold.

I'll unsubscribe from this issue now, but feel free to re-open the GHC issue if you still think that this is a GHC issue.

**Comment by patrickdoc** [comment]
Yeah, I was trying to explain how that logic is intentionally throwing away bad runs, waiting for larger runs.

Basically, the function being benchmarked is run in increasingly larger batch sizes until it runs for a significant amount of time.

If the function takes 1ms, then running it 1000 times should take 1s. We can then divide 1s/1000 runs to get 1ms/run. So the first batches of size 1, 5, 10, 50... Etc. might not be large enough, but eventually you reach a number of iterations that satisfies your threshold.

measTime m should grow with every benchmark loop.

**Comment by RyanGlScott** [comment]
By the way, a simpler way to trigger the same issue is to run `cabal new-run --flag "criterion-measurement +fast"` (which compiles `criterion-measurement` with `-O0`) on the program in https://github.com/bos/criterion/issues/214#issuecomment-516789770.

**Comment by RyanGlScott** [comment]
Note that specifically marking `Criterion.Measurement.Types.Internal` to always be compiled with `-O2`, like so:

```diff
diff --git a/criterion-measurement/src/Criterion/Measurement/Types/Internal.hs b/criterion-measurement/src/Criterion/Measurement/Types/Internal.hs
index f093112..2943c71 100644
--- a/criterion-measurement/src/Criterion/Measurement/Types/Internal.hs
+++ b/criterion-measurement/src/Criterion/Measurement/Types/Internal.hs
@@ -1,4 +1,5 @@
 {-# LANGUAGE BangPatterns #-}
+{-# OPTIONS_GHC -O2 #-}
 {-# OPTIONS_GHC -fno-full-laziness #-}
 -- |
 -- Module      : Criterion.Types.Internal
```

Is sufficient to make the example terminate when `criterion-measurement` is compiled with `+fast`. Unfortunately, it does not fix the issue when `criterion-measurement` is compiled with `-fprof-auto`.

**Comment by RyanGlScott** [comment]
Ah, it turns out that there is a `-fno-prof-auto` flag as well! If I add that to `Criterion.Measurement.Types.Internal` (in addition to `-O2`), then the example _does_ terminate with `-fprof-auto`. In particular, here are the times I get with different combinations of GHC settings:

<details>

* Baseline

  ```
  benchmarking xxx
  time                 8.449 ns   (8.448 ns .. 8.451 ns)
                       1.000 R²   (1.000 R² .. 1.000 R²)
  mean                 8.450 ns   (8.449 ns .. 8.453 ns)
  std dev              6.787 ps   (4.355 ps .. 12.14 ps)
  ```
* `--flags="criterion-measurement +fast"`

  ```
  benchmarking xxx
  time                 8.935 ns   (8.930 ns .. 8.941 ns)
                       1.000 R²   (1.000 R² .. 1.000 R²)
  mean                 8.928 ns   (8.917 ns .. 8.936 ns)
  std dev              31.42 ps   (25.71 ps .. 40.31 ps)
  ```
* `--enable-profiling`

  ```
  benchmarking xxx
  time                 13.75 ns   (13.75 ns .. 13.75 ns)
                       1.000 R²   (1.000 R² .. 1.000 R²)
  mean                 13.75 ns   (13.75 ns .. 13.75 ns)
  std dev              7.327 ps   (5.557 ps .. 10.06 ps)
  ```
* `--enable-profiling --flags="criterion-measurement +fast"`

  ```
  benchmarking xxx
  time                 14.02 ns   (14.01 ns .. 14.02 ns)
                       1.000 R²   (1.000 R² .. 1.000 R²)
  mean                 14.02 ns   (14.02 ns .. 14.03 ns)
  std dev              13.42 ps   (8.661 ps .. 21.93 ps)
  ```
* `--enable-profiling --ghc-options=-fprof-auto`

  ```
  benchmarking xxx
  time                 14.28 ns   (14.28 ns .. 14.28 ns)
                       1.000 R²   (1.000 R² .. 1.000 R²)
  mean                 14.29 ns   (14.28 ns .. 14.29 ns)
  std dev              12.16 ps   (8.866 ps .. 16.13 ps)
  ```
* `--enable-profiling --ghc-options=-fprof-auto --flags="criterion-measurement +fast"`

  ```
  benchmarking xxx
  time                 13.75 ns   (13.75 ns .. 13.75 ns)
                       1.000 R²   (1.000 R² .. 1.000 R²)
  mean                 13.75 ns   (13.75 ns .. 13.76 ns)
  std dev              14.45 ps   (5.844 ps .. 27.72 ps)
  ```
</details>

The presence of profiling (`-fprof-auto` or otherwise) still causes some amount of overhead, but I think it's tolerable. You should expect some amount of runtime overhead when running profiled programs anyway, so I don't think it's worth applying similar hacks to other modules in `criterion-measurement`.

Does this sound like a reasonable hack?

**Comment by patrickdoc** [comment]
Seems reasonable to me. I would guess profiling is safe anywhere except inside the whnf/nf functions.

Also, if I remember correctly I tested with different levels of optimization and I either already forced it somewhere or found that I didn't need it. So you might only need the "-fno-prof-auto." but that is just a hunch, feel free to ignore.

Your 8ns result also lines up with my testing. The fastest result I could find was something like "id 0" which consistently got around 6ns, so the results in your test feel right to me.

**Comment by RyanGlScott** [comment]
> Also, if I remember correctly I tested with different levels of optimization and I either already forced it somewhere or found that I didn't need it. So you might only need the "-fno-prof-auto."

Local experimentation seems to suggest otherwise, as if I enable `-fno-prof-auto` in `Criterion.Measurement.Types.Internal` but _not_ `-O2`, then the benchmark loops forever when `criterion-measurement` is compiled with `+fast`.

In any case, I've opened #215 for this.

**Comment by RyanGlScott** [comment]
I've uploaded [`criterion-measurement-0.1.2.0`](http://hackage.haskell.org/package/criterion-measurement-0.1.2.0) to Hackage with a fix.
