### ISSUE TITLE
Monad(fail) for 1.4.*

### ISSUE THREAD

**Issue by ysangkok** [bos/criterion#222]
The 1.4 branch has a single compilation error on GHC 8.10, I don't know if it is something you still care about, but I thought I'd let yet know. Especially cause I don't know if you get notified when hvr put the base constraint on your package in Hackage. Here is the error:

```
Criterion/Internal.hs:110:3: error:
    • No instance for (MonadFail Criterion)
        arising from a do statement
        with the failable pattern ‘Measurement _ _ meas’
    • In a stmt of a 'do' block:
        Measurement _ _ meas <- runOne i desc bm
      In the expression:
        do Measurement _ _ meas <- runOne i desc bm
           analyseOne i desc meas
      In an equation for ‘runAndAnalyseOne’:
          runAndAnalyseOne i desc bm
            = do Measurement _ _ meas <- runOne i desc bm
                 analyseOne i desc meas
    |
110 |   Measurement _ _ meas <- runOne i desc bm
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Feel free to close! I noticed this because Criterion 1.4 is currently used by the UUID package's benchmark and I didn't manage to upgrade it to 1.5 because of some cyclic dependency.

**Comment by RyanGlScott** [comment]
Thanks for the bug report. I am opting not to fix this for two reasons:

1. Although this may appear to be "a single compilation error", fixing it in `criterion-1.5.*` actually took a surprising amount of effort. In addition to the commits which added a `MonadFail` instance (yes, [multiple](https://github.com/bos/criterion/commit/defb4cd397c48940d507e97f9c62986569572fcd) [commits](https://github.com/bos/criterion/commit/5a50d8761f168082f8d85f921f8188ab53b3dbb0)), I had to do some subsequent cleanup to ensure that this worked on all supported versions of GHC—see commits f8967b8d4f3ac7f9333f8c4fd0fdf1c25201c7bd and b23e2d75fa1497e6da1f2133fe0d7ca87eff3b88. b23e2d75fa1497e6da1f2133fe0d7ca87eff3b88 in particular is tricky because it depends on a particular interaction between a specific `base-compat-batteries` version and `MonadFailDesugaring`, and since `criterion-1.4.*` has different version bounds on `base-compat-batteries` than `criterion-1.5.*` does, it's not clear to me how to backport that commit in a clean way.
2. `criterion-1.4.*` is two years old already. Time to upgrade!
