### ISSUE TITLE
Benchmark can't be properly run on other machine

### ISSUE THREAD

**Issue by vlatkoB** [bos/criterion#45]
Hello,

compiled bin can't be properly run on another machine because of error  ': TemplateNotFound "report.tpl"'. If "templates" dir from .cabal is supplied with bin, and bin run with "-t templates/report.tpl", the report is missing pics.

Ubuntu OS.

Best regards,

vlatko

**Comment by osa1** [comment]
This is not a bug. You need `.cabal/share/<your compiler>/criterion-<version>/templates` too.

**Comment by Gabriel439** [comment]
I think this issue should be re-opened.  The `bench` executable (which wraps `criterion` in a command-line executable) is running into this same problem:

https://github.com/Gabriel439/bench/issues/12

I would like to be able to distribute a standalone executable, but the baked-in runtime reference to the template file makes the `--output` option fail when the executable is distributed to another machine that doesn't have `criterion` installed

**Comment by RyanGlScott** [comment]
Hm. I think I also share @osa1's opinion that this isn't a bug—or at the very least, the issue lies in `Cabal`, not `criterion`.

As you've noted in https://github.com/Gabriel439/bench/issues/12#issuecomment-346892659, `criterion` uses `Cabal`'s `data-files` feature to bundle several large files used for `criterion`'s HTML reporting. This means that one cannot simply copy a `criterion` binary from machine to machine and expect it to work, as the appropriate `data-files` must also be present on the target machine.

For whatever reason, it seems that `brew` is not distributing the `data-files` correctly, leading to the mess in https://github.com/Gabriel439/bench/issues/12. Alas, I cannot offer any advice on how one might fix that, since I know nothing of how `brew` works internally.

(There are extreme measures one can take to eliminate the use of `data-files` entirely, such as by embedding the files directly into source code using the `file-embed` library. But that would massively increase binary sizes—and likely compilation times—so as a result, that's not an avenue I'm willing to pursue.)

**Comment by RyanGlScott** [comment]
One way forward here is to adopt the approach that the `hyphenation` and `pandoc` take: use `file-embed` to embed the `data-files` into the binary when a flag is enabled (`pandoc` calls this `embed_data_files`). This would add some complexity, but perhaps it's unavoidable for now, as I'll admit that I can't find a general solution to the `data-files` problem after doing some searching.

**Comment by RyanGlScott** [comment]
See #169 for an attempt at implementing the idea in https://github.com/bos/criterion/issues/45#issuecomment-346899126.

**Comment by RyanGlScott** [comment]
@Gabriel439, can you confirm if the new `-fembed-data-files` flag works for `bench`'s purposes?

**Comment by Gabriel439** [comment]
@RyanGlScott: Yeah, will do.  Give me a day or two to test this

**Comment by Gabriel439** [comment]
@RyanGlScott: `bench` users confirmed that the new `-fembed-data-files` successfully produces a relocatable `bench` executable: https://github.com/Gabriel439/bench/issues/12#issuecomment-348633222

Thanks a lot for all of your help! 🙂

**Comment by RyanGlScott** [comment]
Awesome! I've uploaded [`criterion-1.2.5.0`](http://hackage.haskell.org/package/criterion-1.2.5.0) to Hackage with these changes.
